const listDogs = [
  "",
  "Affenpinscher",
  "African",
  "Airedale",
  "Akita",
  "Appenzeller",
  "Sheperd Australian",
  "Basenji",
  "Beagle",
  "Bluetick",
  "Borzoi",
  "Bouvier",
  "Boxer",
  "Brabancon",
  "Briard",
  "Norwegian Buhund",
  "Boston Bulldog",
  "English Bulldog",
  "French Bulldog",
  "Staffordshire Bullterrier",
  "Cairn",
  "Australian Cattledog",
  "Chihuahua",
  "Chow",
];
export default listDogs;